// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA70JHdXEu9PFbTyEBqSow2t_ZScfT6ZRE',
    appId: '1:281174583444:web:1ec565202f14833132ac81',
    messagingSenderId: '281174583444',
    projectId: 'altropps',
    authDomain: 'altropps.firebaseapp.com',
    storageBucket: 'altropps.appspot.com',
    measurementId: 'G-VVB3QPJXEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfcJdl7TpupChBtohLw4ufGxen8eb9VGY',
    appId: '1:281174583444:android:d089a8d2a8071f2b32ac81',
    messagingSenderId: '281174583444',
    projectId: 'altropps',
    storageBucket: 'altropps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfzo1PDXUk8H5x3IXSS8fe31vcApvm1L0',
    appId: '1:281174583444:ios:983242a66ac0808232ac81',
    messagingSenderId: '281174583444',
    projectId: 'altropps',
    storageBucket: 'altropps.appspot.com',
    iosClientId: '281174583444-nl647fq5em9ij6cd793n4k7n3bb9frr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.altropps',
  );
}
